CREATE TABLE usages (
	id INT NOT NULL AUTO_INCREMENT,
	uuid VARCHAR(40) NOT NULL,
	time INT,
	ch1 DOUBLE(5,3),
	ch2 DOUBLE(5,3),
	ch3 DOUBLE(5,3),
	ch4 DOUBLE(5,3),
	ch5 DOUBLE(5,3),
	ch6 DOUBLE(5,3),
	ch7 DOUBLE(5,3),
	ch8 DOUBLE(5,3),
	ch9 DOUBLE(5,3),
	ch10 DOUBLE(5,3),
	ch11 DOUBLE(5,3),
	ch12 DOUBLE(5,3),
	PRIMARY KEY (id)
);


CREATE TABLE devices (
	id INT NOT NULL AUTO_INCREMENT,
	uuid VARCHAR(40) NOT NULL,
	name VARCHAR(20),
	ch1 VARCHAR(40),
	ch2 VARCHAR(40),
	ch3 VARCHAR(40),
	ch4 VARCHAR(40),
	ch5 VARCHAR(40),
	ch6 VARCHAR(40),
	ch7 VARCHAR(40),
	ch8 VARCHAR(40),
	ch9 VARCHAR(40),
	ch10 VARCHAR(40),
	ch11 VARCHAR(40),
	ch12 VARCHAR(40),
	PRIMARY KEY (id)
);

CREATE TABLE channels (
	id INT NOT NULL AUTO_INCREMENT,
	deviceID VARCHAR(40) NOT NULL,
	channelID VARCHAR(40) NOT NULL,
	name VARCHAR(20),
	PRIMARY KEY (id)
);

CREATE TABLE groupings (
	id INT NOT NULL AUTO_INCREMENT,
	groupID VARCHAR(40) NOT NULL,
	uuid VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE groups (
	id INT NOT NULL AUTO_INCREMENT,
	groupID VARCHAR(40) NOT NULL,
	name VARCHAR(20),
	PRIMARY KEY (id)
);